/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Lcd_Juego.h"
#include "C_Blancas_aliases.h"
#include "C_Blancas.h"
#include "C_Negras_aliases.h"
#include "C_Negras.h"
#include "isr_Blancas.h"
#include "isr_Negras.h"
#include "Tiempos_aliases.h"
#include "Tiempos.h"
#include "isr_Tiempos.h"
#include "Aceptar_aliases.h"
#include "Aceptar.h"
#include "isr_Aceptar.h"
#include "timer_clock.h"
#include "Timer_1.h"
#include "isr_Timer.h"
#include "B_Blancas_aliases.h"
#include "B_Blancas.h"
#include "isr_B_Blancas.h"
#include "isr_N_Negras.h"
#include "N_Negras_aliases.h"
#include "N_Negras.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "Lcd_Juego_LCDPort_aliases.h"
#include "Lcd_Juego_LCDPort.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

